version: '3'
services:
  flyway:
    container_name: flyway-container
    image: flyway/flyway:6.3.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./Server/EventsApp/sql_versions:/flyway/sql
      - ./Server/EventsApp/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql-container
    image: postgres:9
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:

  spring-boot-app:
    container_name: spring-boot-container
    build:
      context: ./Server/EventsApp
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_MAIL_HOST:
      SPRING_MAIL_PORT:
      SPRING_MAIL_EMAIL:
      SPRING_MAIL_PASSWORD:

  react-app:
    container_name: react-container
    build:
      context: ./Frontend/events-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  jenkins:
    container_name: jenkins-container
    image: jenkins/jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
